export const categoryLabels = {
  ko: {
    work: '업무/조건',
    profile: '지원 정보',
    strength: '역량 표현',
    people: '직장 관계',
    company: '회사 선택',
  },
  vi: {
    work: 'Cong viec / dieu kien',
    profile: 'Thong tin co ban',
    strength: 'Bieu hien nang luc',
    people: 'Quan he noi cong so',
    company: 'Lua chon cong ty',
  },
};

export const phaseLabels = {
  'Xem ho so': '서류 검토',
  'Hoa hop nhom': '팀 적합도',
  'Thich nghi nhanh': '빠른 적응',
  'Kinh nghiem truoc day': '이전 경험',
  'Cau truc to chuc': '조직 이해',
  'Quan he noi lam viec': '직장 관계',
  'Tom tat diem manh': '강점 소개',
  'Tieu chi chon cong ty': '회사 선택',
  'Can bang cuoc song': '워라밸',
  'Quy mo doanh nghiep': '기업 규모',
  'Thong tin ho so': '지원 정보',
  'So sanh dai ngo': '보상 표현',
};

export const vocabulary = [
  { id: 'part-time', term: '아르바이트', translation: 'lam them ban thoi gian', glossKo: '정해진 시간 동안 임시로 하는 일.', glossVi: 'Cong viec tam thoi hoac ban thoi gian lam theo gio.', category: 'work' },
  { id: 'work-hours', term: '근무 시간', translation: 'gio lam viec', glossKo: '일을 하는 정해진 시간.', glossVi: 'Khoang thoi gian quy dinh de lam viec.', category: 'work' },
  { id: 'duties', term: '업무', translation: 'nhiem vu cong viec', glossKo: '직장에서 맡아서 하는 일.', glossVi: 'Cong viec hoac nhiem vu minh phu trach trong cong ty.', category: 'work' },
  { id: 'hourly-pay', term: '시급', translation: 'luong theo gio', glossKo: '한 시간 일하고 받는 돈.', glossVi: 'So tien nhan duoc cho moi gio lam viec.', category: 'work' },
  { id: 'gender', term: '성별', translation: 'gioi tinh', glossKo: '남자와 여자의 구분.', glossVi: 'Thong tin co ban ve gioi tinh cua ung vien.', category: 'profile' },
  { id: 'age', term: '연령', translation: 'do tuoi', glossKo: '나이.', glossVi: 'Thong tin ve tuoi tac hay nhom tuoi.', category: 'profile' },
  { id: 'sincere', term: '성실하다', translation: 'cham chi va tan tam', glossKo: '정성스럽고 참된 태도로 일하는 것.', glossVi: 'Lam viec nghiem tuc, deu dan va co trach nhiem.', category: 'strength' },
  { id: 'meticulous', term: '꼼꼼하다', translation: 'can than, ti mi', glossKo: '빈틈이 없이 자세하고 차분한 것.', glossVi: 'Lam viec ky luong, it bo sot chi tiet.', category: 'strength' },
  { id: 'experienced', term: '경험이 많다', translation: 'co nhieu kinh nghiem', glossKo: '어떤 일을 많이 해 본 것.', glossVi: 'Da trai qua va thuc hanh cong viec nhieu lan.', category: 'strength' },
  { id: 'skilled', term: '실력이 있다', translation: 'co nang luc tot', glossKo: '어떤 일을 잘 할 수 있는 능력이 있는 것.', glossVi: 'Co ky nang va kha nang thuc hien cong viec tot.', category: 'strength' },
  { id: 'quick-learner', term: '이해가 빠르다', translation: 'tiep thu nhanh', glossKo: '다른 사람의 말이나 상황을 빨리 알아듣는 것.', glossVi: 'Nam bat huong dan va tinh huong mot cach nhanh chong.', category: 'strength' },
  { id: 'do-best', term: '최선을 다하다', translation: 'co gang het suc', glossKo: '자신의 모든 힘과 노력을 다하는 것.', glossVi: 'Dung toan bo no luc va kha nang de lam viec.', category: 'strength' },
  { id: 'report-writing', term: '보고서 작성을 잘하다', translation: 'gioi viet bao cao', glossKo: '보고 문서를 잘 만드는 것.', glossVi: 'Co kha nang viet va sap xep bao cao ro rang.', category: 'strength' },
  { id: 'people-skills', term: '대인 관계가 원만하다', translation: 'giao tiep va quan he tot', glossKo: '다른 사람들과 사이좋게 잘 지내는 것.', glossVi: 'De hoa hop va hop tac voi nguoi khac.', category: 'strength' },
  { id: 'new-hire', term: '신입 사원', translation: 'nhan vien moi', glossKo: '회사에 새로 들어온 직원.', glossVi: 'Nguoi moi vao cong ty va bat dau lam viec.', category: 'people' },
  { id: 'colleague', term: '동료', translation: 'dong nghiep', glossKo: '직장에서 직급이 비슷하거나 같은 사람.', glossVi: 'Nguoi lam viec cung ban trong cong ty.', category: 'people' },
  { id: 'supervisor', term: '직장 상사', translation: 'cap tren noi lam viec', glossKo: '직장에서 자기보다 직급이 높은 사람.', glossVi: 'Nguoi co chuc vu cao hon va huong dan cong viec.', category: 'people' },
  { id: 'subordinate', term: '부하 직원', translation: 'nhan vien cap duoi', glossKo: '직장에서 자기보다 직급이 낮은 사람.', glossVi: 'Nguoi lam viec duoi su quan ly cua minh.', category: 'people' },
  { id: 'assistant-manager', term: '대리', translation: 'tro ly quan ly', glossKo: '과장 아래의 직급.', glossVi: 'Chuc danh nam duoi gwajang trong he thong chuc vu Han Quoc.', category: 'people' },
  { id: 'section-chief', term: '과장', translation: 'quan ly cap trung', glossKo: '부장 아래, 대리 위의 직급.', glossVi: 'Chuc danh nam tren daeri va duoi bujang.', category: 'people' },
  { id: 'department-head', term: '부장', translation: 'truong bo phan', glossKo: '회사의 한 부서를 책임지는 사람.', glossVi: 'Nguoi phu trach mot bo phan trong cong ty.', category: 'people' },
  { id: 'major-company', term: '대기업', translation: 'cong ty lon', glossKo: '규모가 아주 큰 회사.', glossVi: 'Cong ty quy mo lon hoac tap doan lon.', category: 'company' },
  { id: 'small-company', term: '중소기업', translation: 'doanh nghiep vua va nho', glossKo: '규모가 크지 않은 회사.', glossVi: 'Cong ty co quy mo nho hon, thuong can lam nhieu vai tro.', category: 'company' },
  { id: 'high-annual-salary', term: '연봉이 높다', translation: 'luong nam cao', glossKo: '일 년 동안 받는 월급이 많은 것.', glossVi: 'Tong thu nhap hang nam o muc cao.', category: 'company' },
  { id: 'flexible-commute', term: '출퇴근 시간이 자유롭다', translation: 'gio di ve linh hoat', glossKo: '회사에 오고 가는 시간이 자유로운 것.', glossVi: 'Thoi gian den cong ty va tan lam co the linh hoat.', category: 'company' },
  { id: 'promotion-chances', term: '승진 기회가 많다', translation: 'nhieu co hoi thang tien', glossKo: '직급이 올라갈 기회가 많은 것.', glossVi: 'De co co hoi len chuc vu cao hon.', category: 'company' },
  { id: 'long-vacation', term: '휴가가 길다', translation: 'ky nghi dai', glossKo: '쉴 수 있는 날이 긴 것.', glossVi: 'So ngay nghi phep hoac nghi ngoi dai hon.', category: 'company' },
];

export const interviewDeck = [
  {
    id: 'document-strength',
    phaseVi: 'Xem ho so',
    title: '문서 실무 포지션',
    titleVi: 'Vi tri chu yeu lam tai lieu va bao cao',
    situation: '마케팅 기획팀 최종 인터뷰. 보고 자료와 문서 커뮤니케이션 비중이 큰 포지션입니다.',
    situationVi: 'Phong van cuoi cung cho nhom lap ke hoach marketing. Day la vi tri dung nhieu tai lieu va bao cao.',
    question: '문서 중심 업무에 가장 설득력 있는 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi thuyet phuc nhat cho cong viec thien ve tai lieu.',
    interviewerLine: '우리 팀은 회의 자료와 보고 문서를 자주 씁니다. 본인의 강점을 한 문장으로 말해 보세요.',
    interviewerLineVi: 'Nhom cua chung toi thuong xuyen dung tai lieu hop va van ban bao cao. Hay noi diem manh cua ban trong mot cau.',
    choices: [
      { id: 'a', label: '저는 보고서 작성을 잘하고 꼼꼼한 편입니다.', translation: 'Toi viet bao cao tot va lam viec kha ti mi.', relatedTerms: ['report-writing', 'meticulous'] },
      { id: 'b', label: '저는 휴가가 길고 연봉이 높은 회사만 찾습니다.', translation: 'Toi chi tim cong ty co ky nghi dai va luong nam cao.', relatedTerms: ['long-vacation', 'high-annual-salary'] },
      { id: 'c', label: '저는 부하 직원이 많아야 일하기 편합니다.', translation: 'Toi thay de lam viec hon khi co nhieu nhan vien cap duoi.', relatedTerms: ['subordinate'] },
      { id: 'd', label: '저는 성별과 연령이 제일 중요하다고 생각합니다.', translation: 'Toi cho rang gioi tinh va do tuoi la dieu quan trong nhat.', relatedTerms: ['gender', 'age'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['report-writing', 'meticulous'],
    explanation: '문서 업무에서는 보고서 작성 능력과 꼼꼼함을 함께 보여 주는 표현이 가장 자연스럽습니다.',
    explanationVi: 'Voi cong viec thien ve tai lieu, cach noi ve kha nang viet bao cao va su ti mi la tu nhien nhat.',
    successLine: '좋습니다. 실무 적응력이 바로 떠오르는 대답이네요.',
    successLineVi: 'Rat tot. Cau nay lam ro ngay kha nang thich nghi voi cong viec thuc te.',
    failureLine: '강점보다 조건이나 위계만 말하면 직무 적합도가 약하게 들립니다.',
    failureLineVi: 'Neu chi noi dieu kien hoac cap bac, muc do phu hop voi vi tri se nghe yeu hon.',
  },
  {
    id: 'team-fit',
    phaseVi: 'Hoa hop nhom',
    title: '협업 적합도',
    titleVi: 'Muc do phu hop khi hop tac',
    situation: '여러 부서와 동시에 프로젝트를 진행하는 조직입니다.',
    situationVi: 'Day la to chuc thuong phai phoi hop du an cung luc voi nhieu phong ban.',
    question: '협업 맥락에 가장 잘 맞는 표현을 고르세요.',
    questionVi: 'Hay chon bieu hien phu hop nhat voi boi canh hop tac.',
    interviewerLine: '신입 사원이더라도 여러 팀과 협업해야 합니다. 어떤 점을 강조하시겠어요?',
    interviewerLineVi: 'Ngay ca nhan vien moi cung phai hop tac voi nhieu nhom. Ban se nhan manh diem nao?',
    choices: [
      { id: 'a', label: '대인 관계가 원만해서 동료와 협업할 때 강점이 있습니다.', translation: 'Toi co quan he giao tiep tot nen co diem manh khi hop tac voi dong nghiep.', relatedTerms: ['people-skills', 'colleague'] },
      { id: 'b', label: '저는 과장보다 먼저 승진하는 것이 중요합니다.', translation: 'Viec thang chuc truoc cap quan ly moi la dieu quan trong voi toi.', relatedTerms: ['section-chief', 'promotion-chances'] },
      { id: 'c', label: '저는 시급만 높으면 어떤 일이든 괜찮습니다.', translation: 'Chi can luong theo gio cao thi cong viec nao cung duoc.', relatedTerms: ['hourly-pay'] },
      { id: 'd', label: '저는 연령과 성별을 먼저 확인합니다.', translation: 'Toi luon kiem tra tuoi va gioi tinh truoc tien.', relatedTerms: ['age', 'gender'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['people-skills', 'colleague'],
    explanation: '협업을 묻는 질문에는 인간관계와 동료 협업 표현을 직접 연결하는 것이 좋습니다.',
    explanationVi: 'Khi duoc hoi ve hop tac, nen tra loi truc tiep bang cach lien ket giao tiep voi lam viec cung dong doi.',
    successLine: '팀 적응력과 소통 감각이 잘 드러났습니다.',
    successLineVi: 'Ban da the hien ro kha nang hoa nhap nhom va giao tiep.',
    failureLine: '협업 질문에는 보상이나 개인정보보다 사람과의 관계 표현이 핵심입니다.',
    failureLineVi: 'Trong cau hoi ve hop tac, dieu quan trong la quan he voi con nguoi chu khong phai dai ngo.',
  },
  {
    id: 'adaptability',
    phaseVi: 'Thich nghi nhanh',
    title: '빠른 적응력',
    titleVi: 'Kha nang thich nghi nhanh',
    situation: '신규 시스템 교육 기간이 짧고, 초반 학습 속도가 중요한 환경입니다.',
    situationVi: 'Thoi gian hoc he thong moi rat ngan, toc do tiep thu ban dau la yeu to quan trong.',
    question: '학습 속도와 태도를 가장 잘 보여 주는 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi the hien ro nhat toc do hoc va thai do lam viec.',
    interviewerLine: '새로운 시스템을 빨리 익혀야 하는데, 어떻게 자신을 설명할 수 있습니까?',
    interviewerLineVi: 'Ban se phai nhanh chong hoc he thong moi. Ban co the mo ta ban than nhu the nao?',
    choices: [
      { id: 'a', label: '저는 이해가 빠르고 맡은 일에 최선을 다합니다.', translation: 'Toi tiep thu nhanh va luon co gang het suc voi cong viec duoc giao.', relatedTerms: ['quick-learner', 'do-best'] },
      { id: 'b', label: '저는 출퇴근 시간이 자유로우면 더 잘할 수 있습니다.', translation: 'Neu gio di ve linh hoat thi toi se lam tot hon.', relatedTerms: ['flexible-commute'] },
      { id: 'c', label: '저는 직장 상사보다 부하 직원을 더 좋아합니다.', translation: 'Toi thich nhan vien cap duoi hon cap tren.', relatedTerms: ['supervisor', 'subordinate'] },
      { id: 'd', label: '저는 대기업보다 중소기업이라는 단어가 더 멋있습니다.', translation: 'Toi thay tu doanh nghiep vua va nho nghe hay hon cong ty lon.', relatedTerms: ['major-company', 'small-company'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['quick-learner', 'do-best'],
    explanation: '적응력 질문에는 이해 속도와 태도를 함께 제시해야 설득력이 생깁니다.',
    explanationVi: 'Khi noi ve kha nang thich nghi, nen cho thay ca toc do tiep thu lan thai do lam viec.',
    successLine: '초기 온보딩에서 강점을 보여 주는 답변이었습니다.',
    successLineVi: 'Cau tra loi nay the hien tot suc manh o giai doan bat dau cong viec.',
    failureLine: '적응력 질문은 근무 조건보다 학습 속도와 태도를 중심으로 답해야 합니다.',
    failureLineVi: 'Cau hoi ve thich nghi can tap trung vao viec hoc nhanh va thai do, khong phai dieu kien lam viec.',
  },
  {
    id: 'work-history',
    phaseVi: 'Kinh nghiem truoc day',
    title: '이전 경험 정리',
    titleVi: 'Tom tat kinh nghiem truoc day',
    situation: '지원자는 학생 시절 실무 경험을 쌓은 적이 있습니다.',
    situationVi: 'Ung vien da tung tich luy mot so kinh nghiem thuc te tu thoi sinh vien.',
    question: '아르바이트 경험을 직무 역량으로 연결하는 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi biet lien ket kinh nghiem lam them voi nang luc cong viec.',
    interviewerLine: '이전에 어떤 경험이 있었는지 실무 중심으로 말해 보세요.',
    interviewerLineVi: 'Hay noi ve kinh nghiem truoc day cua ban theo huong cong viec thuc te.',
    choices: [
      { id: 'a', label: '아르바이트를 하면서 근무 시간과 업무를 성실하게 관리했습니다.', translation: 'Khi lam them, toi da quan ly gio lam va cong viec mot cach cham chi.', relatedTerms: ['part-time', 'work-hours', 'duties', 'sincere'] },
      { id: 'b', label: '대리와 과장 직급 차이를 자세히 압니다.', translation: 'Toi biet ro su khac nhau giua cap daeri va gwajang.', relatedTerms: ['assistant-manager', 'section-chief'] },
      { id: 'c', label: '휴가가 길면 어떤 업무든 잘 맞을 것 같습니다.', translation: 'Neu ky nghi dai thi co le cong viec nao cung hop voi toi.', relatedTerms: ['long-vacation', 'duties'] },
      { id: 'd', label: '성별과 연령을 기준으로 동료를 기억합니다.', translation: 'Toi thuong nho dong nghiep theo gioi tinh va do tuoi.', relatedTerms: ['gender', 'age', 'colleague'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['part-time', 'work-hours', 'duties', 'sincere'],
    explanation: '이전 경험을 설명할 때는 실제로 맡았던 일과 근무 관리 경험을 함께 제시하는 것이 좋습니다.',
    explanationVi: 'Khi noi ve kinh nghiem truoc day, nen de cap ca cong viec da lam va cach ban quan ly cong viec.',
    successLine: '짧은 경력도 실무 경험으로 잘 번역했습니다.',
    successLineVi: 'Ban da chuyen duoc kinh nghiem ngan hanh thanh nang luc thuc te.',
    failureLine: '경험 질문에는 직급 설명보다 실제로 했던 일과 태도가 더 중요합니다.',
    failureLineVi: 'Cau hoi ve kinh nghiem can noi ro viec da lam va thai do, thay vi chi giai thich cap bac.',
  },
  {
    id: 'org-structure',
    phaseVi: 'Cau truc to chuc',
    title: '조직 구조 이해',
    titleVi: 'Hieu ve cau truc to chuc',
    situation: '지원 부서는 위계와 보고 체계를 중요하게 봅니다.',
    situationVi: 'Bo phan ung tuyen danh gia cao viec hieu he thong cap bac va bao cao.',
    question: '직급 설명이 정확한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi giai thich dung ve cap bac.',
    interviewerLine: '조직 구조를 이해하고 있는지도 중요합니다. 아래 설명 중 맞는 것은 무엇입니까?',
    interviewerLineVi: 'Viec hieu cau truc to chuc cung rat quan trong. Trong cac mo ta duoi day, dau la mo ta dung?',
    choices: [
      { id: 'a', label: '부장은 한 부서를 책임지고, 과장은 그 아래, 대리는 과장 아래 직급입니다.', translation: 'Bujang phu trach mot bo phan, ben duoi la gwajang, va daeri o duoi gwajang.', relatedTerms: ['department-head', 'section-chief', 'assistant-manager'] },
      { id: 'b', label: '대리는 부장보다 높고, 과장은 신입 사원 아래입니다.', translation: 'Daeri cao hon bujang, con gwajang lai o duoi nhan vien moi.', relatedTerms: ['assistant-manager', 'department-head', 'new-hire'] },
      { id: 'c', label: '동료는 모두 직장 상사보다 높은 직급입니다.', translation: 'Tat ca dong nghiep deu co cap bac cao hon cap tren.', relatedTerms: ['colleague', 'supervisor'] },
      { id: 'd', label: '중소기업에서는 직급이 전혀 필요 없습니다.', translation: 'Trong doanh nghiep vua va nho, cap bac hoan toan khong can thiet.', relatedTerms: ['small-company'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['department-head', 'section-chief', 'assistant-manager'],
    explanation: '부장-과장-대리의 상대적인 위치를 정확히 말하면 조직 이해도가 잘 드러납니다.',
    explanationVi: 'Neu ban mo ta dung vi tri tuong doi cua bujang, gwajang, daeri, nguoi nghe se thay ban hieu to chuc.',
    successLine: '보고 체계를 빠르게 이해하는 인상입니다.',
    successLineVi: 'Ban da tao duoc an tuong la nguoi hieu nhanh he thong bao cao.',
    failureLine: '직급의 상대적 위치를 잘못 말하면 조직 이해도가 떨어져 보입니다.',
    failureLineVi: 'Noi sai vi tri cap bac se lam giam muc do tin cay ve viec hieu to chuc.',
  },
  {
    id: 'relationship-map',
    phaseVi: 'Quan he noi lam viec',
    title: '직장 관계 설명',
    titleVi: 'Mo ta quan he noi cong so',
    situation: '입사 후 바로 팀 커뮤니케이션에 들어가야 하는 상황입니다.',
    situationVi: 'Sau khi vao cong ty, ban se phai giao tiep ngay voi cac thanh vien trong nhom.',
    question: '사람 관계를 가장 정확하게 설명한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi mo ta dung nhat cac moi quan he giua con nguoi.',
    interviewerLine: '팀 안에서 사람 관계를 설명해 보세요.',
    interviewerLineVi: 'Hay thu mo ta cac moi quan he giua moi nguoi trong nhom.',
    choices: [
      { id: 'a', label: '직장 상사는 제 위의 사람이고, 부하 직원은 제 아래에서 함께 일하는 사람입니다.', translation: 'Cap tren la nguoi o vi tri cao hon toi, con nhan vien cap duoi la nguoi lam viec duoi su quan ly cua toi.', relatedTerms: ['supervisor', 'subordinate'] },
      { id: 'b', label: '동료는 항상 부장보다 높은 사람입니다.', translation: 'Dong nghiep luon la nguoi co cap bac cao hon bujang.', relatedTerms: ['colleague', 'department-head'] },
      { id: 'c', label: '신입 사원은 모두 과장과 같은 직급입니다.', translation: 'Tat ca nhan vien moi deu co cung cap bac voi gwajang.', relatedTerms: ['new-hire', 'section-chief'] },
      { id: 'd', label: '대기업에서는 동료가 필요 없고 상사만 있으면 됩니다.', translation: 'O cong ty lon, chi can cap tren ma khong can dong nghiep.', relatedTerms: ['major-company', 'colleague', 'supervisor'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['supervisor', 'subordinate'],
    explanation: '상사와 부하 직원의 관계를 정확히 설명해야 직장 내 관계 어휘를 안정적으로 쓸 수 있습니다.',
    explanationVi: 'Tu vung ve quan he noi lam viec can duoc dung chinh xac theo vai tro va cap bac.',
    successLine: '직장 관계 어휘를 차분하게 정리했습니다.',
    successLineVi: 'Ban da sap xep duoc tu vung ve quan he cong so mot cach ro rang.',
    failureLine: '직장 관계 표현은 직급과 역할을 정확히 구분하는 것이 핵심입니다.',
    failureLineVi: 'Cac cach noi ve cap tren, dong nghiep va cap duoi can duoc phan biet that chinh xac.',
  },
  {
    id: 'strength-compression',
    phaseVi: 'Tom tat diem manh',
    title: '강점 압축 소개',
    titleVi: 'Gioi thieu ngan gon ve diem manh',
    situation: '짧은 자기소개 안에 핵심 역량을 압축해야 하는 순간입니다.',
    situationVi: 'Ban can tom tat nang luc chinh trong mot phan tu gioi thieu ngan.',
    question: '업무 수행 역량을 가장 자연스럽게 압축한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi tom tat nang luc lam viec mot cach tu nhien nhat.',
    interviewerLine: '자신의 업무 수행 능력을 세 가지 표현으로 압축해 보세요.',
    interviewerLineVi: 'Hay nen nang luc lam viec cua ban thanh ba bieu hien ngan gon.',
    choices: [
      { id: 'a', label: '저는 성실하고 경험이 많으며 실력이 있다고 말씀드릴 수 있습니다.', translation: 'Toi co the noi rang minh cham chi, co nhieu kinh nghiem va co nang luc tot.', relatedTerms: ['sincere', 'experienced', 'skilled'] },
      { id: 'b', label: '저는 대기업과 중소기업을 둘 다 좋아합니다.', translation: 'Toi deu thich ca cong ty lon lan doanh nghiep vua va nho.', relatedTerms: ['major-company', 'small-company'] },
      { id: 'c', label: '저는 시급과 휴가만 좋으면 더 성장합니다.', translation: 'Chi can luong theo gio va ky nghi tot thi toi se phat trien hon.', relatedTerms: ['hourly-pay', 'long-vacation'] },
      { id: 'd', label: '저는 부하 직원보다 연령이 많으면 좋겠습니다.', translation: 'Toi muon minh lon tuoi hon nhan vien cap duoi.', relatedTerms: ['subordinate', 'age'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['sincere', 'experienced', 'skilled'],
    explanation: '태도, 경험, 실력을 한 묶음으로 제시하면 핵심 역량을 간결하게 압축할 수 있습니다.',
    explanationVi: 'Khi tu gioi thieu ngan gon, nen gom thai do, kinh nghiem va nang luc thanh mot nhom.',
    successLine: '역량 소개가 짧고 단단하게 정리됐습니다.',
    successLineVi: 'Ban da tom tat diem manh ngan gon ma chac chan.',
    failureLine: '강점 소개는 조건보다 태도와 경험, 실력 표현이 중심이어야 합니다.',
    failureLineVi: 'Phan gioi thieu diem manh nen dat trong tam vao nang luc, khong phai dieu kien hay so thich.',
  },
  {
    id: 'growth-company',
    phaseVi: 'Tieu chi chon cong ty',
    title: '성장 중심 회사 선택',
    titleVi: 'Chon cong ty theo huong phat trien',
    situation: '지원자는 커리어 성장 가능성을 중시합니다.',
    situationVi: 'Ung vien xem trong kha nang phat trien su nghiep trong tuong lai.',
    question: '성장 중심 선호를 가장 잘 드러내는 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi the hien ro nhat xu huong uu tien su phat trien.',
    interviewerLine: '성장 중심으로 회사를 고른다면 어떤 회사를 선호합니까?',
    interviewerLineVi: 'Neu chon cong ty theo huong phat trien su nghiep, ban se thich loai cong ty nao?',
    choices: [
      { id: 'a', label: '승진 기회가 많고 연봉이 높은 대기업에 관심이 있습니다.', translation: 'Toi quan tam den cong ty lon co nhieu co hoi thang tien va luong nam cao.', relatedTerms: ['promotion-chances', 'high-annual-salary', 'major-company'] },
      { id: 'b', label: '성별과 연령이 비슷한 회사가 좋습니다.', translation: 'Toi thich cong ty co nhan vien co gioi tinh va do tuoi giong minh.', relatedTerms: ['gender', 'age'] },
      { id: 'c', label: '부장보다 대리가 많은 회사가 좋습니다.', translation: 'Toi thich cong ty co nhieu daeri hon bujang.', relatedTerms: ['department-head', 'assistant-manager'] },
      { id: 'd', label: '시급만 높으면 신입 사원도 괜찮습니다.', translation: 'Chi can luong theo gio cao thi lam nhan vien moi cung duoc.', relatedTerms: ['hourly-pay', 'new-hire'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['promotion-chances', 'high-annual-salary', 'major-company'],
    explanation: '성장 중심 선택에서는 승진 기회, 보상, 회사 규모를 자연스럽게 연결하는 것이 좋습니다.',
    explanationVi: 'Neu muon nhan manh su phat trien, nen noi lien mach giua co hoi thang tien, dai ngo va quy mo cong ty.',
    successLine: '커리어 동기가 분명하게 들립니다.',
    successLineVi: 'Dong luc phat trien su nghiep cua ban duoc the hien rat ro.',
    failureLine: '성장 중심 질문에는 보상과 기회, 회사 규모 표현이 함께 들어가야 자연스럽습니다.',
    failureLineVi: 'Cau hoi nay can nhac den co hoi, dai ngo va quy mo cong ty mot cach tu nhien.',
  },
  {
    id: 'work-life-balance',
    phaseVi: 'Can bang cuoc song',
    title: '워라밸 조건 설명',
    titleVi: 'Mo ta dieu kien can bang cong viec va cuoc song',
    situation: '지원자는 장기적으로 지속 가능한 근무 환경도 중요하게 생각합니다.',
    situationVi: 'Ung vien cung xem trong mot moi truong lam viec co the duy tri lau dai.',
    question: '워라밸 관점에 가장 잘 맞는 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi phu hop nhat voi goc nhin can bang cong viec va cuoc song.',
    interviewerLine: '워라밸 관점에서는 어떤 조건이 좋습니까?',
    interviewerLineVi: 'Xet theo can bang cong viec va cuoc song, ban thay dieu kien nao la tot?',
    choices: [
      { id: 'a', label: '출퇴근 시간이 자유롭고 휴가가 긴 회사가 좋습니다.', translation: 'Toi thich cong ty co gio di ve linh hoat va ky nghi dai.', relatedTerms: ['flexible-commute', 'long-vacation'] },
      { id: 'b', label: '직장 상사와 부하 직원만 많으면 좋습니다.', translation: 'Chi can co nhieu cap tren va nhan vien cap duoi la duoc.', relatedTerms: ['supervisor', 'subordinate'] },
      { id: 'c', label: '과장과 대리 직급 이름이 멋있으면 좋습니다.', translation: 'Toi thay tot neu ten cap bac gwajang va daeri nghe hay.', relatedTerms: ['section-chief', 'assistant-manager'] },
      { id: 'd', label: '성실하다와 꼼꼼하다를 회사 조건으로 봅니다.', translation: 'Toi xem cham chi va ti mi la dieu kien cua cong ty.', relatedTerms: ['sincere', 'meticulous'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['flexible-commute', 'long-vacation'],
    explanation: '워라밸 질문에는 근무 자율성과 휴가처럼 생활과 직접 연결되는 표현이 적절합니다.',
    explanationVi: 'Khi noi ve work-life balance, nen dung nhung bieu hien lien quan truc tiep den thoi gian va nghi ngoi.',
    successLine: '개인의 기준을 또렷하게 설명했습니다.',
    successLineVi: 'Ban da giai thich ro tieu chuan ca nhan cua minh.',
    failureLine: '워라밸은 성격이나 직급보다 근무 조건 표현으로 답해야 자연스럽습니다.',
    failureLineVi: 'Can bang cong viec va cuoc song nen duoc tra loi bang dieu kien lam viec, khong phai tinh cach hay cap bac.',
  },
  {
    id: 'small-company-fit',
    phaseVi: 'Quy mo doanh nghiep',
    title: '중소기업 지원 이유',
    titleVi: 'Ly do ung tuyen vao doanh nghiep vua va nho',
    situation: '작은 조직에서 여러 역할을 맡아야 하는 포지션입니다.',
    situationVi: 'Day la vi tri trong to chuc nho, noi ban se phai dam nhan nhieu vai tro.',
    question: '중소기업 지원 이유로 가장 적절한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi phu hop nhat khi giai thich ly do ung tuyen vao doanh nghiep vua va nho.',
    interviewerLine: '중소기업을 지원하는 이유를 말해 보세요.',
    interviewerLineVi: 'Hay noi ly do tai sao ban ung tuyen vao doanh nghiep vua va nho.',
    choices: [
      { id: 'a', label: '중소기업에서는 다양한 업무를 맡아 경험을 넓히기 좋다고 생각합니다.', translation: 'Toi nghi o doanh nghiep vua va nho minh co the dam nhan nhieu cong viec va mo rong kinh nghiem.', relatedTerms: ['small-company', 'duties', 'experienced'] },
      { id: 'b', label: '중소기업은 부장이 없어서 편할 것 같습니다.', translation: 'Toi nghi doanh nghiep vua va nho se de lam viec vi khong co bujang.', relatedTerms: ['small-company', 'department-head'] },
      { id: 'c', label: '중소기업은 연령과 성별을 덜 본다고 들었습니다.', translation: 'Toi nghe rang doanh nghiep vua va nho it xem tuoi va gioi tinh hon.', relatedTerms: ['small-company', 'age', 'gender'] },
      { id: 'd', label: '중소기업은 시급이 높아서 정규직보다 좋습니다.', translation: 'Doanh nghiep vua va nho tot hon vi luong theo gio cao hon nhan vien chinh thuc.', relatedTerms: ['small-company', 'hourly-pay'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['small-company', 'duties', 'experienced'],
    explanation: '중소기업 지원 이유는 다양한 업무 경험과 성장 가능성으로 연결하는 것이 자연스럽습니다.',
    explanationVi: 'Ly do ung tuyen vao doanh nghiep vua va nho se tu nhien hon neu gan voi viec mo rong kinh nghiem va dam nhan nhieu nhiem vu.',
    successLine: '회사 규모에 대한 이해와 동기가 함께 드러났습니다.',
    successLineVi: 'Ban da cho thay minh hieu ro quy mo cong ty va dong luc phat trien.',
    failureLine: '회사 규모 질문에는 직무 경험 확대와 성장 관점을 담는 편이 좋습니다.',
    failureLineVi: 'Cau hoi ve quy mo cong ty nen duoc tra loi bang goc nhin hoc hoi va mo rong vai tro.',
  },
  {
    id: 'profile-basics',
    phaseVi: 'Thong tin ho so',
    title: '지원서 기본 정보',
    titleVi: 'Thong tin co ban trong don ung tuyen',
    situation: '기초 행정 정보를 확인하는 간단한 문답입니다.',
    situationVi: 'Day la phan hoi dap ngan de xac nhan thong tin hanh chinh co ban.',
    question: '지원서 기본 항목을 가장 적절하게 설명한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi mo ta dung nhat cac muc thong tin co ban trong ho so.',
    interviewerLine: '지원서에 들어가는 기본 항목을 이야기해 보세요.',
    interviewerLineVi: 'Hay noi ve cac muc thong tin co ban thuong xuat hien trong don ung tuyen.',
    choices: [
      { id: 'a', label: '지원서에는 성별과 연령 같은 기본 정보를 적습니다.', translation: 'Trong don ung tuyen, nguoi ta ghi cac thong tin co ban nhu gioi tinh va do tuoi.', relatedTerms: ['gender', 'age'] },
      { id: 'b', label: '지원서에는 과장과 부장의 관계만 적습니다.', translation: 'Trong ho so, chi can ghi moi quan he giua gwajang va bujang.', relatedTerms: ['section-chief', 'department-head'] },
      { id: 'c', label: '지원서에는 연봉과 휴가만 적습니다.', translation: 'Trong don ung tuyen, chi can ghi luong nam va ky nghi.', relatedTerms: ['high-annual-salary', 'long-vacation'] },
      { id: 'd', label: '지원서에는 대인 관계가 원만하다만 쓰면 됩니다.', translation: 'Chi can viet rang minh giao tiep tot la du.', relatedTerms: ['people-skills'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['gender', 'age'],
    explanation: '성별, 연령처럼 기초 프로필 정보를 묻는 상황에서는 지원서 항목으로 설명하는 것이 가장 자연스럽습니다.',
    explanationVi: 'Trong tinh huong hoi ve thong tin co ban, cach noi tu nhien nhat la nhac den cac muc trong ho so nhu gioi tinh va do tuoi.',
    successLine: '기본 행정 표현도 안정적으로 다루고 있습니다.',
    successLineVi: 'Ngay ca nhung bieu hien hanh chinh co ban ban cung da dung kha on.',
    failureLine: '기본 정보 질문에는 직급이나 조건보다 프로필 항목을 말해야 합니다.',
    failureLineVi: 'Cau hoi nay can noi den thong tin ca nhan co ban, khong phai cap bac hay dai ngo.',
  },
  {
    id: 'compensation-language',
    phaseVi: 'So sanh dai ngo',
    title: '보상 표현 비교',
    titleVi: 'So sanh cach noi ve dai ngo',
    situation: '아르바이트와 정규직 표현을 구분해 말해야 합니다.',
    situationVi: 'Ban can biet phan biet cach noi giua cong viec lam them va viec chinh thuc.',
    question: '보상 표현을 가장 정확하게 비교한 답변을 고르세요.',
    questionVi: 'Hay chon cau tra loi so sanh dung nhat cac bieu hien ve dai ngo.',
    interviewerLine: '아르바이트와 정규직 보상 표현을 비교해 보세요.',
    interviewerLineVi: 'Hay thu so sanh cach noi ve dai ngo giua viec lam them va viec chinh thuc.',
    choices: [
      { id: 'a', label: '아르바이트는 시급을 많이 보고, 정규직은 연봉을 더 중요하게 봅니다.', translation: 'Voi viec lam them, nguoi ta thuong quan tam den luong theo gio; con viec chinh thuc thi luong nam quan trong hon.', relatedTerms: ['part-time', 'hourly-pay', 'high-annual-salary'] },
      { id: 'b', label: '아르바이트는 부장이 되고, 정규직은 대리가 됩니다.', translation: 'Lam them thi thanh bujang, con viec chinh thuc thi thanh daeri.', relatedTerms: ['part-time', 'department-head', 'assistant-manager'] },
      { id: 'c', label: '아르바이트는 성별을 보고, 정규직은 연령을 봅니다.', translation: 'Lam them thi xem gioi tinh, con viec chinh thuc thi xem do tuoi.', relatedTerms: ['part-time', 'gender', 'age'] },
      { id: 'd', label: '아르바이트는 휴가를 보고, 정규직은 동료를 봅니다.', translation: 'Lam them thi xem ky nghi, con viec chinh thuc thi xem dong nghiep.', relatedTerms: ['part-time', 'long-vacation', 'colleague'] },
    ],
    correctChoiceId: 'a',
    focusTerms: ['part-time', 'hourly-pay', 'high-annual-salary'],
    explanation: '아르바이트와 정규직의 보상 표현은 시급과 연봉으로 대비해 말하는 것이 가장 정확합니다.',
    explanationVi: 'Cach so sanh ro rang nhat la dat 시급 va 연봉 doi lap voi nhau theo tung loai cong viec.',
    successLine: '보상 표현의 쓰임 차이를 잘 구분했습니다.',
    successLineVi: 'Ban da phan biet dung cach dung cua tu vung ve dai ngo.',
    failureLine: '보상 표현 비교는 시급과 연봉을 축으로 설명해야 분명해집니다.',
    failureLineVi: 'Khi so sanh dai ngo, truc chinh la luong theo gio va luong nam.',
  },
];
